# -*- coding: utf-8 -*-
"""apppp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q-PL0jFI57zhNPPuSLVGwKePhKy7DuQS
"""

import streamlit as st
import pandas as pd
import joblib
from joblib import load
import pickle
import os

# Load model
model = joblib.load('xgboost_personality_model.joblib')

# Judul halaman
st.set_page_config(page_title="Prediksi Personality", layout="centered")

# Sidebar untuk navigasi
page = st.sidebar.selectbox("Navigasi", ["Pendahuluan", "Model", "Prediksi", "Anggota Kelompok"])

# 1. Halaman Pendahuluan
if page == "Pendahuluan":
    st.title("📊 Pendahuluan")
    st.write("""
    Dataset ini berisi data kepribadian yang digunakan untuk mengklasifikasikan seseorang sebagai *Introvert* atau *Extrovert* berdasarkan beberapa fitur sosial seperti:
    
    - Waktu sendirian
    - Kehadiran di acara sosial
    - Ukuran lingkaran pertemanan
    - Frekuensi posting
    - Perasaan lelah setelah bersosialisasi
    - Rasa takut tampil
    
    Dataset terdiri dari 5000 data dan telah digunakan untuk melatih model XGBoost.
    """)
    
    # Tampilkan sampel data
    df = pd.read_csv("personality_dataset.csv")
    st.dataframe(df.head())

# 2. Halaman Model
elif page == "Model":
    st.title("🧠 Model Machine Learning")
    st.write("""
    Model yang digunakan adalah **XGBoost Classifier**, dilatih dengan akurasi lebih dari **99%**.

    Model dilatih pada fitur:
    - Time_spent_Alone
    - Stage_fear
    - Social_event_attendance
    - Going_outside
    - Drained_after_socializing
    - Friends_circle_size
    - Post_frequency
    """)
    st.success("Model berhasil dimuat dan siap digunakan untuk prediksi.")

# 3. Halaman Prediksi
elif page == "Prediksi":
    st.title("🔮 Prediksi Kepribadian")

    # Form input data
    with st.form("prediction_form"):
        alone = st.slider("waktu yang dihabiskan sendirian (0–10)", 0, 10, 5)
        stage_fear = st.selectbox("demam panggung?", ["Yes", "No"])
        social_event = st.slider("kehadiran acara sosial (0–10)", 0, 10, 5)
        going_outside = st.slider("pergi ke luar (0–10)", 0, 10, 5)
        drained = st.selectbox("cape setelah bersosialisasi?", ["Yes", "No"])
        friends = st.slider("circle pertemanan (0–20)", 0, 20, 10)
        post_freq = st.slider("frekuensi posting (0–10)", 0, 10, 5)

        submit = st.form_submit_button("Prediksi")

    if submit:
        # Konversi kategori ke angka sesuai training
        stage_fear_bin = 1 if stage_fear == "Yes" else 0
        drained_bin = 1 if drained == "Yes" else 0

        input_data = [[alone, stage_fear_bin, social_event, going_outside,
                       drained_bin, friends, post_freq]]

        pred = model.predict(input_data)[0]
        personality = "Extrovert" if pred == 1 else "Introvert"

        st.subheader("Hasil Prediksi")
        st.info(f"Model memprediksi kepribadian: **{personality}**")

# 4. Halaman Anggota Kelompok
elif page == "Anggota Kelompok":
    st.title("👥 Anggota Kelompok")
    st.write("""
    1. Nama 1 - NIM
    2. Nama 2 - NIM
    3. Nama 3 - NIM
    4. Nama 4 - NIM
    """)
